#
service: callcenter
frameworkVersion: "=1.32.0"
provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, env:STAGE}
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - arn:aws:s3:::${self:service}-rec-data-${self:provider.stage}/*
  environment:
    STAGE: ${self:provider.stage}
    GOOGLE_APPLICATION_CREDENTIALS: credentials.json

package:
  exclude:
    - "**"
  include:
    - handler.py
    - callcenter.py
    - credentials.json

functions:
  record:
    handler: handler.record
    memorySize: 256
    timeout: 60
    events:
      - http:
          path: record
          method: post
  callback:
    handler: handler.callback
    memorySize: 256
    timeout: 60
    events:
      - http:
          path: callback
          method: post

resources:
  Resources:
    RecDataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-rec-data-${self:provider.stage}
        AccessControl: Private
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        VersioningConfiguration:
          Status: Enabled
  Outputs:
    RecDataBucketName:
      Value:
        Ref: RecDataBucket

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
